Командная работа над проектом. Добавить новые фичи в проект
giperionos/java-filmorate pull request #17
Opened 2022-07-21 20:30 UTC by giperionos

В рамках данного PR реализованы следующие фичи:
1. Функциональность «Поиск»
2. Функциональность  «Отзывы»
3. Функциональность «Лента событий» 
4. Добавление режиссёров в фильмы 
5. Функциональность «Рекомендации»
6. Функциональность «Общие фильмы»
7. Вывод самых популярных фильмов по жанру и годам
8. Удаление фильмов и пользователей

2022-07-22 18:35 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +import javax.validation.ValidationException;
этот импорт  не используется в классе, нужно удалить

2022-07-22 18:37 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final EventType EVENT_LIKE = EventType.of(1, "LIKE");
константы должны идти первыми в списке полей класса
и правильнее будет назвать LIKE_EVENT, потому что потом еще могут быть DISLIKE_EVENT и тд, и это все будет ивенты

2022-07-22 18:42 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                Operation.of(2, "ADD"))
лучше все используемые тут операции тоже сделать константами, потому что новый разработчик может создать в другом месте `Operation.of(1, "ADD")` и нарушится консистентность

2022-07-22 18:48 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    //GET /films/director/{directorId}?sortBy=[year,likes]
нужно либо сделать javadoc комментарий, либо удалить 
этот комментарий добавлен из-за того, что неочевидно, как задавать сортировку  через параметр sortBy
поэтому лучше сделать его поведение очевидным, чем описывать как это работает

как это можно сделать:
можно например сделать, чтобы значение переданное в sortBy парсилось в enum, а сам енум будет содержать все доступные в приложении сортировки
```
enum SortType {
   SORT_BY_YEAR_ASC,
   SORT_BY_YEAR_DESC,
   SORT_BY_LIKES_ASC,
   SORT_BY_LIKES_DESC
}
```

2022-07-22 18:49 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    private static final EventType EVENT_REVIEW = EventType.of(2, "REVIEW");
нужно также изменить порядок и название
`REVIEW_EVENT_TYPE`

2022-07-22 18:50 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.debug("Добавление POST запроса /reviews");
в логи стоит добавлять хоть какую-то инфу про данные, с которыми происходит работа
`log.debug("Добавлено новое ревью. Id: {}", reviewId)`

2022-07-22 18:52 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Review updateReview (@Valid @RequestBody Review review) {
нужно убрать лишний пробел после названия метода
можно применить автоформат кода в идее _CTRL ALT L_

2022-07-22 18:52 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public List<Review> getAllReviewes(@RequestParam (defaultValue = "10") Integer count,
пробелы после аннотаций перед их аргументами не нужны

2022-07-22 18:54 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +                                        @RequestParam (required = false) Long filmId) {
у метода getAll не должно быть такого параметра, как id, потому что метод должен всегда выдавать все объекты
для получения объекта по ид нужно иметь отдельный метод `getReviewById(String id)`

2022-07-22 18:56 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                Operation.of(2, "ADD"))
те же замечания с константами и названиями

2022-07-22 18:57 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<Film> getRecommendations(@PathVariable Long id) {
тут для id нужно дать более говорящее название, потому что из контекста сложно понять, ид чего нужно передать, чтобы получить рекомендацию

лучше `userId`
и в аннотации у пути тоже исправить

2022-07-22 19:00 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Getter
все эти аннотации можно заменить одной @Data

2022-07-22 19:01 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    public Director(Integer id, String name) {
конструктор можно заменить аннотацией ломбока

2022-07-22 19:02 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    private final Long entityId;
тут сложно понять, что хранится в entityId и чем это значение отличается от eventId

2022-07-22 19:07 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    public Map<String, Object> getEvent() {
какой-то костыль для выдачи в апи

странные константы в сервисах и такой маппинг в мапу можно было бы исправить, просто используя для eventType и operation енумы с нужными значениями

но тут еще может быть не так легко заменить на енумы, потому что в бд хранится другая структура
в общем, это вам на подумать

2022-07-22 19:08 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/EventType.java
> +    Integer id;
поля должны быть private

2022-07-22 19:09 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return Objects.hash(name, description, releaseDate, duration, mpa.getId());
при изменении реализации вычисления хешкода должна была поменяться и реализация equals

2022-07-22 19:10 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmDirector.java
> +@Getter
можно заменить эти аннотации на Data

2022-07-22 19:10 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmDirector.java
> +    public FilmDirector(Long filmId, Integer directorId) {
можно заменить аннотацией

2022-07-22 19:11 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Operation.java
> +@Value(staticConstructor = "of")
на data классах все используют разные аннотации, у кого-то конструкторы, у кого-то of
вам нужно договориться и делать в едином стиле

2022-07-22 19:12 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Boolean isPositive;
название должно быть без is
is добавляется у геттеров у boolean полей

2022-07-22 19:13 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int useful = 0;
если это рейтинг полезности, нужно дать более понятное имя - usefulRating или usefulScore

2022-07-22 19:13 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +   /* public boolean getIsPositive() {
неиспользуемый код нужно удалять

2022-07-22 19:15 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/UsefulReview.java
> +public class UsefulReview {
по названию кажется, что это наследник класса Review
нужно дать более понятное название UsefulReviewEvent или что-то подобное

2022-07-22 19:17 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/event/EventService.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
в DirectorService конструктор объявлен другим способом
хочется, чтобы конструкции, выполняющие одинаковые функции, выглядели тоже одинаково

2022-07-22 19:19 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private void addFilmDirectorToDB(Film film, boolean needCleanBeforeAdd) {
чтобы не делать вариативность через boolean параметр  можно просто сделать 2 отдельных метода на разные случаи
это будет более правильно с точки зрения архитектуры

2022-07-22 19:20 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        //заполнить объекты  Режиссерово в составе объекта Film
опечатка

2022-07-22 19:20 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private void addFilmDirectorToDB(Film film, boolean needCleanBeforeAdd) {
в остальных методах тоже стоит убрать параметр needCleanBeforeAdd

2022-07-22 19:21 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +            case "year":
нужно использовать константы для этих значений
но более правильно будет сделать енум для сортировок (писал в контроллере комент к этому)

2022-07-22 19:29 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +public interface DirectorStorage {
нужно привести к единой иерархии стораджи и их нейминг
потому что сейчас есть интерфейсы и имплементации для каждого типа entity
а еще есть интерфейс Storage, от которого тоже некоторые стораджи зависят

я бы убрал Storage и для каждого типа объектов делал отдельные интерфейсы с нужным набором методов
а имплементации называл так: UserStorage интерфейс и UserStorageDbImpl, UserStorageInMemoryImpl - реализации

2022-07-22 19:34 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +    public List<Film> getFilmsByQuery(String query, String by) {
по таким названиям аргументов абсолютно не понятно, что в них должен передавать пользователь этого класса

публичное апи класса должно быть максимально детерменированым и понятным, тут же просто есть 2 строки на входе с неясными допустимыми значениями у них

2022-07-22 19:36 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/impl/ReviewDBStorage.java
> +public class ReviewDBStorage implements ReviewStorage {
названия классов должны быть в CamelCase, сокращения тоже Db, Http и тд

2022-07-22 19:36 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/impl/ReviewDBStorage.java
> +
пустая строка перед закрывающей скобкой не нужна

2022-07-22 19:39 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/usefulReview/UsefulReviewStorage.java
> +    boolean addLikeReview(Long id, Long userId);
стоит проверить все интерфейсы стораджей, чтобы названия  тоже были не просто из слов add(), update(), delete(), а как тут более детальные

2022-07-22 19:41 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorageTest.java
> +                null,
лучше завести переменные  для таких значений, потому что не понятно в какое поле присвоен null
```
String name = null;
Integer age = null;
```
и в такой ситуации  уже было бы не `User(null, null)`, а `User(name, age)`

2022-07-22 19:45 UTC, makholin requested changes
Нужно привести код проекта к единому стилю и исправить другие замечания
Также на новые сервисы стоит написать тесты, чтобы запустив их можно было убедиться, что ничего не сломано

2022-07-23 07:05 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +import javax.validation.ValidationException;
Кто делает: Толстых  
Что и как делает: Убрать строку.

2022-07-23 07:16 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final EventType EVENT_LIKE = EventType.of(1, "LIKE");
Кто делает:  Алексей М.
Что и как делает: В рамках рефакторинга Event. Убрать константу.

2022-07-23 07:17 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                Operation.of(2, "ADD"))
Кто делает: Алексей М.
Что и как делает: В рамках рефакторинга Event. Убрать создание объекта.

2022-07-23 07:17 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    private static final EventType EVENT_REVIEW = EventType.of(2, "REVIEW");
Кто делает: Алексей М.
Что и как делает: В рамках рефакторинга Event. Убрать константу.

2022-07-23 07:17 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                Operation.of(2, "ADD"))
Кто делает: Алексей М.
Что и как делает: В рамках рефакторинга Event. Убрать создание объекта.

2022-07-23 07:18 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    public Map<String, Object> getEvent() {
Кто делает: Алексей М.
Что и как делает: В рамках рефакторинга Event. Заменить на Enum

2022-07-23 07:21 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/EventType.java
> +    Integer id;
Кто делает: Алексей М.
Что и как делает: Делается в рамках рефакторинга.

2022-07-23 07:23 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Operation.java
> +@Value(staticConstructor = "of")
Кто делает: Алексей М.
Что и как делает: В рамках рефакторинга Event.

2022-07-23 07:25 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/service/event/EventService.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
Кто делает: Алексей М.
Что и как делает: поменять на обычный конструктор.

2022-07-23 07:29 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    //GET /films/director/{directorId}?sortBy=[year,likes]
Кто делает: Толстых
Что и как делает: сделать через Enum  или сделать комментарий

2022-07-23 07:31 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.debug("Добавление POST запроса /reviews");
Кто делает: Алексей
Что и как делает: поправить

2022-07-23 07:31 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Review updateReview (@Valid @RequestBody Review review) {
Кто делает: Алексей С.
Что и как делает: поправить

2022-07-23 07:31 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public List<Review> getAllReviewes(@RequestParam (defaultValue = "10") Integer count,
Кто делает: Алексей С.
Что и как делает: поправить

2022-07-23 07:31 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +                                        @RequestParam (required = false) Long filmId) {
Кто делает: Алексей С.
Что и как делает: поправить

2022-07-23 07:32 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<Film> getRecommendations(@PathVariable Long id) {
Кто делает: Толстых
Что и как делает: переименовать переменные по всему проекту, где нужно

2022-07-23 07:33 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Getter
Кто делает: Толстых
Что и как делает: дать комментарий обратный

2022-07-23 07:36 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    public Director(Integer id, String name) {
Кто делает: Толстых
Что и как делает: исправить

2022-07-23 07:41 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    private final Long entityId;
Кто делает: Толстых
Что и как делает: Дать комментарий.

2022-07-23 07:41 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return Objects.hash(name, description, releaseDate, duration, mpa.getId());
Кто делает: Толстых
Что и как делает: поправить

2022-07-23 07:41 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmDirector.java
> +@Getter
Кто делает: Толстых
Что и как делает: поправить

2022-07-23 07:42 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmDirector.java
> +    public FilmDirector(Long filmId, Integer directorId) {
Кто делает: Толстых
Что и как делает: поправить

2022-07-23 07:43 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Boolean isPositive;
Кто делает: Толстых
Что и как делает: коменнтариий

2022-07-23 07:44 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int useful = 0;
Кто делает: Алексей С
Что и как делает: поправить

2022-07-23 07:44 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +   /* public boolean getIsPositive() {
Кто делает: Алексей С
Что и как делает: поправить

2022-07-23 07:44 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/UsefulReview.java
> +public class UsefulReview {
Кто делает: Алексей С
Что и как делает: поправить

2022-07-23 07:44 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private void addFilmDirectorToDB(Film film, boolean needCleanBeforeAdd) {
Кто делает: Толстых
Что и как делает: поправить

2022-07-23 07:45 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        //заполнить объекты  Режиссерово в составе объекта Film
Кто делает: Толстых
Что и как делает: поправить

2022-07-23 07:45 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +            case "year":
Кто делает: Толстых
Что и как делает: поправить

2022-07-23 07:48 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +public interface DirectorStorage {
Кто делает: Толстых
Что и как делает: исправить

2022-07-23 07:48 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +    public List<Film> getFilmsByQuery(String query, String by) {
Кто делает: Алексей М.
Что и как делает: поправить

2022-07-23 07:49 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/impl/ReviewDBStorage.java
> +public class ReviewDBStorage implements ReviewStorage {
Кто делает: Алексей С
Что и как делает: поправить

2022-07-23 07:49 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/impl/ReviewDBStorage.java
> +
Кто делает: Алексей С
Что и как делает: поправить

2022-07-23 07:50 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/storage/usefulReview/UsefulReviewStorage.java
> +    boolean addLikeReview(Long id, Long userId);
Кто делает: Толстых
Что и как делает: поправить

2022-07-23 07:50 UTC, giperionos commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorageTest.java
> +                null,
Кто делает: Толстых
Что и как делает: поправить

2022-07-23 09:43 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +import javax.validation.ValidationException;
Исправлено.

2022-07-23 11:15 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +            case "year":
Исправлено.

2022-07-23 11:54 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +public interface DirectorStorage {
Исправлено.

2022-07-23 11:54 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/storage/usefulReview/UsefulReviewStorage.java
> +    boolean addLikeReview(Long id, Long userId);
Исправлено!

2022-07-23 11:58 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    //GET /films/director/{directorId}?sortBy=[year,likes]
Реализовал вариант с использованием Enum.

2022-07-23 11:59 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<Film> getRecommendations(@PathVariable Long id) {
Исправил - сделал в проекте название более понятные!

2022-07-23 12:00 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Getter
Исправил.

2022-07-23 12:01 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    public Director(Integer id, String name) {
Исправил.

2022-07-23 12:12 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return Objects.hash(name, description, releaseDate, duration, mpa.getId());
Исправил! Согласовал реализацию hashCode и equals между собой.

2022-07-23 12:14 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmDirector.java
> +@Getter
Исправил!

2022-07-23 12:14 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmDirector.java
> +    public FilmDirector(Long filmId, Integer directorId) {
Исправил!

2022-07-23 12:18 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        //заполнить объекты  Режиссерово в составе объекта Film
Исправлено!

2022-07-23 12:47 UTC, giperionos commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorageTest.java
> +                null,
Исправлено!

2022-07-23 13:05 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private void addFilmDirectorToDB(Film film, boolean needCleanBeforeAdd) {
Реализавал вариант с раздельными методами!
Исправлено.

2022-07-23 16:48 UTC, AlexeyMurenkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                Operation.of(2, "ADD"))
Готово

2022-07-23 16:49 UTC, AlexeyMurenkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    public Map<String, Object> getEvent() {
Готово.

2022-07-23 16:49 UTC, AlexeyMurenkov commented on src/main/java/ru/yandex/practicum/filmorate/model/EventType.java
> +    Integer id;
Готово.

2022-07-23 16:49 UTC, AlexeyMurenkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Operation.java
> +@Value(staticConstructor = "of")
Готово.

2022-07-23 16:50 UTC, AlexeyMurenkov commented on src/main/java/ru/yandex/practicum/filmorate/service/event/EventService.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
Готово.

2022-07-23 17:02 UTC, AlexeyVlz commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int useful = 0;
Здесь название также взято из ТЗ
Объект в Json выглядит так:
{
“reviewId”: 123,
“content”: “This film is sooo baad.”,
“isPositive”: false,
“userId”: 123, // Пользователь
“filmId”: 2, // Фильм
“useful”: 20 // рейтинг полезности
}

2022-07-23 17:05 UTC, AlexeyMurenkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +    public List<Film> getFilmsByQuery(String query, String by) {
Успел сделать до меня Александр Т.

2022-07-24 08:46 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final EventType EVENT_LIKE = EventType.of(1, "LIKE");
В рамках рефакторинга от Алексея М. данная константа удалена.

2022-07-24 08:47 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                Operation.of(2, "ADD"))
Исправлено в рамках рефакторинга от Алексей М.

2022-07-24 08:48 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    private static final EventType EVENT_REVIEW = EventType.of(2, "REVIEW");
В рамках рефакторинга от Алексея М. данная константа удалена.

2022-07-24 08:48 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Review updateReview (@Valid @RequestBody Review review) {
Исправлено.

2022-07-24 08:56 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/impl/ReviewDBStorage.java
> +public class ReviewDBStorage implements ReviewStorage {
Исправлено.

2022-07-24 17:56 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.debug("Добавление POST запроса /reviews");
Реализовано.

2022-07-24 17:56 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public List<Review> getAllReviewes(@RequestParam (defaultValue = "10") Integer count,
Исправлено.

2022-07-24 17:57 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +                                        @RequestParam (required = false) Long filmId) {
Исправлено!

2022-07-24 17:57 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/UsefulReview.java
> +public class UsefulReview {
Исправлено!

2022-07-24 17:58 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/impl/ReviewDBStorage.java
> +
Исправлено.

2022-07-24 18:21 UTC, giperionos commented
> Нужно привести код проекта к единому стилю и исправить другие замечания Также на новые сервисы стоит написать тесты, чтобы запустив их можно было убедиться, что ничего не сломано

Все замечания исправили! Провели большой рефакторинг проекта в части названий классов, названий переменных и т.д.
Дополнительно тесты на сервисы пока делать не стали, т.к. по согласованию с тех. лидом мы юнит-тесты пока не пишем , т.к. это задача последующих спринтов, где будет показано как это делать корректно.

2022-07-25 18:38 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/RatingController.java
> +    public MPARating getByMPARatingId(@PathVariable Integer ratingMpaId) {
сокращения в названиях тоже должны быть в camelCase
например getHttpRequest, getGpsData и тд

тут надо `getByMpaRatingId`

2022-07-25 18:41 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Long id;
в классе поля должны быть перед конструкторами

конструкторы после всех полей, но перед остальными методами

2022-07-25 18:46 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/event/impl/EventStorageDbImpl.java
> +    @Autowired
нужно разделить пустой строкой

2022-07-25 18:46 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/event/impl/EventStorageDbImpl.java
> +    private final JdbcTemplate jdbcTemplate;
нужно разделить пустой строкой

2022-07-25 18:51 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmGenreStorageDbImplTest.java
> +    private static Long film1_id = null;
если это константы, то стоит их сделать final и писать названия в UPPER_CASE
иначе стоит убрать статик и назвать в camelCase

2022-07-25 18:55 UTC, makholin requested changes
хорошо поработали над исправлениями, нужно исправить оставшиеся замечания

еще в ПР нет класса `MPARating`, но его тоже стоило бы привести к общепринятому формату - `MpaRating`

2022-07-26 12:04 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/RatingController.java
> +    public MPARating getByMPARatingId(@PathVariable Integer ratingMpaId) {
Исправлено!

2022-07-26 12:17 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Long id;
Исправлено!

2022-07-26 12:17 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/storage/event/impl/EventStorageDbImpl.java
> +    private final JdbcTemplate jdbcTemplate;
Исправлено!

2022-07-26 12:58 UTC, giperionos commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmGenreStorageDbImplTest.java
> +    private static Long film1_id = null;
Переделал static в обычные переменные. 
Исправлено!

2022-07-26 16:03 UTC, giperionos commented
> хорошо поработали над исправлениями, нужно исправить оставшиеся замечания
> 
> еще в ПР нет класса `MPARating`, но его тоже стоило бы привести к общепринятому формату - `MpaRating`

Класс MpaRating привёл к общепринятому формату, упустил при предыдущем рефакторинге.

2022-07-26 18:25 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/RatingController.java
> +    public MPARating getByMPARatingId(@PathVariable Integer ratingMpaId) {
названия методов тоже надо сделать правильными `getByMpaRatingId`

2022-07-26 18:26 UTC, makholin approved these changes
Работа принята

но названия методов нужно тоже исправить, можно в следующем спринте

2022-07-27 06:16 UTC, giperionos commented on src/main/java/ru/yandex/practicum/filmorate/controller/RatingController.java
> +    public MPARating getByMPARatingId(@PathVariable Integer ratingMpaId) {
В последнем коммите этот метод выглядит так: 
public MpaRating getByMpaRatingId(@PathVariable Integer ratingMpaId) 
Также еще есть такой метод: public List<MpaRating> getAllMpaRatings()
Т.е. названия методов, где участвует Mpa уже исправлены в последнем коммите.

2022-07-31 13:07 UTC, merged